trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - script: |
      java -version
      mvnw.cmd -B verify
    displayName: Build and run tests

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/surefire-reports/TEST-*.xml'